name: "Lattespirit"
description: "Lattespirit"
url: "http://www.lattespirit.com"
paginate: 20
markdown: rdiscount
duoshuo: lattespirit
disqus: lattespirit
permalink: /:title/
highlighter: rouge
safe: true
auto: true
